version: '3'

services:

  project_fortis_interfaces:
    image: cwolff/project_fortis_interfaces:${BUILD_TAG}
    build:
      context: project-fortis-interfaces
      dockerfile: docker/Dockerfile
    ports:
      - ${PROJECT_FORTIS_INTERFACES_PORT}:3000
      - 35729:35729
    environment:
      - REACT_APP_SERVICE_HOST=${PROJECT_FORTIS_SERVICES_HOST}
      - REACT_APP_AD_CLIENT_ID=${AD_CLIENT_ID}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env-secrets
    volumes:
      - ./project-fortis-interfaces/src:/app/src

  project_fortis_services:
    image: cwolff/project_fortis_services:${BUILD_TAG}
    build:
      context: project-fortis-services
      dockerfile: docker/Dockerfile
    ports:
      - ${PROJECT_FORTIS_SERVICES_PORT}:80
    links:
      - cassandra:cassandra
    environment:
      - CASSANDRA_CONTACT_POINTS=${CASSANDRA_HOST}
      - FORTIS_CASSANDRA_SEED_DATA_URL=${CASSANDRA_SEED_DATA_URL}
      - FORTIS_CASSANDRA_SITE_NAME=${CASSANDRA_SITE_NAME}
      - FORTIS_CASSANDRA_SITE_TYPE=${CASSANDRA_SITE_TYPE}
      - FORTIS_CASSANDRA_USERS=${USERS}
      - FORTIS_CASSANDRA_ADMINS=${ADMINS}
      - FORTIS_CASSANDRA_REPLICATION_FACTOR=1
      - AD_CLIENT_ID=${AD_CLIENT_ID}
      - AD_LOG_LEVEL=info
    env_file:
      - .env-secrets

  project_fortis_spark:
    image: cwolff/project_fortis_spark:${BUILD_TAG}
    build:
      context: project-fortis-spark
      dockerfile: docker/Dockerfile
    ports:
      - ${PROJECT_FORTIS_SPARK_CONTEXT_UI_PORT}:4040
      - ${PROJECT_FORTIS_SPARK_MASTER_UI_PORT}:8080
      - ${PROJECT_FORTIS_SPARK_WORKER_UI_PORT}:8081
    links:
      - cassandra:cassandra
    depends_on:
      - project_fortis_services
    environment:
      - FORTIS_CASSANDRA_HOST=${CASSANDRA_HOST}
    env_file:
      - .env-secrets

  cassandra:
    image: erikschlegel/cassandra:v12
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
