version: '3'

services:

  project_fortis_interfaces:
    image: cwolff/project_fortis_interfaces
    build:
      context: project-fortis-interfaces
      dockerfile: docker/Dockerfile
    ports:
      - ${PROJECT_FORTIS_INTERFACES_PORT}:80
    depends_on:
      - project_fortis_services
    environment:
      - REACT_APP_SERVICE_HOST=${PROJECT_FORTIS_SERVICES_HOST}

  project_fortis_services:
    image: cwolff/project_fortis_services
    build:
      context: project-fortis-services
      dockerfile: docker/Dockerfile
    ports:
      - ${PROJECT_FORTIS_SERVICES_PORT}:80
    links:
      - cassandra:cassandra
    environment:
      - CASSANDRA_CONTACT_POINTS=${CASSANDRA_HOST}

  project_fortis_spark:
    image: cwolff/project_fortis_spark
    build:
      context: project-fortis-spark
      dockerfile: docker/Dockerfile
    ports:
      - ${PROJECT_FORTIS_SPARK_CONTEXT_UI_PORT}:4040
      - ${PROJECT_FORTIS_SPARK_MASTER_UI_PORT}:8080
      - ${PROJECT_FORTIS_SPARK_WORKER_UI_PORT}:8081
    links:
      - cassandra:cassandra
    environment:
      - FORTIS_CASSANDRA_HOST=${CASSANDRA_HOST}

  cassandra:
    image: cassandra:3.11.0
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
