version: '3'

services:

  project_fortis_interfaces:
    build:
      context: project-fortis-interfaces
      dockerfile: docker/project-fortis-interfaces/Dockerfile
    ports:
      - 8888:80
    depends_on:
      - project_fortis_services
    environment:
      - REACT_APP_SERVICE_HOST=http://localhost:8080

  project_fortis_services:
    build:
      context: project-fortis-services
      dockerfile: docker/project-fortis-services/Dockerfile
    ports:
      - 8080:80
    links:
      - cassandra:cassandra
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra

  cassandra:
    image: cassandra:3.11.0
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
