apiVersion: v1
kind: Service
metadata:
  name: {{.Values.Master.Component}}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Values.Master.Component}}"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
    - port: {{.Values.Master.ServicePort}}
      targetPort: {{.Values.Master.ContainerPort}}
      name: spark
    - port: {{.Values.WebUi.ServicePort}}
      targetPort: {{.Values.WebUi.ContainerPort}}
      name: http
  selector:
    component: "{{.Values.Master.Component}}"
  type: "LoadBalancer"